### GET user by username
GET http://localhost:3030/api/v1/account/koi04


### GET user by email
GET http://localhost:3030/api/v1/account
Content-Type: application/json

{
  "email": "koi@gmail.com"
}

