### CREATE new user
POST http://localhost:3030/api/v1/account
Content-Type: application/json

{
  "email": "hello@khoi.com",
  "password": "123456"
}


### DELETE a user
POST http://localhost:3030/api/v1/account/delete
Content-Type: application/json

{
  "username": "khoi"
}

### UPDATE a user
POST http://localhost:3030/api/v1/account/update
Content-Type: application/json

{
  "username": "user-1722385917616",
  "update": {
    "account": {
      "username": "koi04",
      "email": "koi@gmail.com"
    },
    "profile": {
      "profile_name": "Love coconut"
    }
  }
}
