###  POST: Register a new account
POST http://localhost:3030/api/v1/auth/register
Content-Type: application/json

{
  "email": "aws.koi04@gmail.com",
  "password": "123456",
  "confirmPassword": "123456"
}

### POST: Verify account
POST http://localhost:3030/api/v1/auth/verify/cba20aa1339efa29389cb98df8fa23f0
Content-Type: application/json


### POST: RESET PASSWORD
POST http://localhost:3030/api/v1/auth/reset-password?token=a3a1780a0929e5d77cb0743e32bb259d
Content-Type: application/json

{
  "update": {
    "password": "67890",
    "confirmPassword": "67890 "
  }
}

### POST: LOG IN
POST http://localhost:3030/api/v1/auth/login
Content-Type: application/json

{
  "email": "aws.koi04@gmail.com",
  "password": "123456"
}

### POST: LOG OUT
POST http://localhost:3030/api/v1/auth/logout

### POST: FORGOT PASSWORD
POST http://localhost:3030/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "aws.koi04@gmail.com"
}

### POST: REFRESH
POST http://localhost:3030/api/v1/auth/refresh
