### CREATE new profile
POST http://localhost:3030/api/v1/profile
Content-Type: application/json

{
  "account_id": "4119c89b-0daa-4acc-ae18-b39ea83bf46b",
  "profile_alias": "khoinguyen",
  "phone_number": "1"
}

### DELETE a profile
POST http://localhost:3030/api/v1/profile/delete
Content-Type: application/json

{
  "profile_alias": "khoinguyendang"
}

### Update a profile
POST http://localhost:3030/api/v1/profile/update
Content-Type: application/json

{
  "profile_alias": "khoinguyen",
  "update": {
    "profile_alias": "khoinguyendang"
  }
}
